Resources:
    Ec2Instance:
        Type: AWS::EC2::Instance
        Properties:
          SecurityGroups:
            - !Ref InstanceSecurityGroup
          KeyName: WFH
          ImageId: ami-05695932c5299858a
          InstanceType: t2.micro
          AvailabilityZone: ap-south-1a
          UserData: !Base64 |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
            cd /var/www/html
            echo "<html><h1>HELLO</h1></html>" > index.html
    InstanceSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
          GroupDescription: Enable SSH access via port 22
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: '80'
              ToPort: '80'
              CidrIp: 0.0.0.0/0